name: SimplyMines
version: '1.1.0'
main: me.simplyran.simplymines.SimplyMines
api-version: '1.21'
soft-depend:
  - Nexo
  - ItemsAdder
  - PlaceholderAPI
  - CraftEngine

commands:
  sm:
    aliases:
      - simplymines
      - simplymine
    description: SimplyMines

